#ifndef __SMARTHOME_H_
#define __SMARTHOME_H_
#define ENDPOINT_ID_SMARTHOME 0X01
#define PROFILE_ID_SMARTHOME 0X501
#define DEVICE_ID_COORDINATOR 0X01
#define DEVICE_ID_SENSOR 0X02
#define DEVIDE_VERSION_ID 0X0

#define ENDJOINNET_CMD_ID 0X1
#define DATA_SEND_CMD_ID  0X2
#define TOGGLE_CMD_ID  0X3
#define  HEART_BEAT_MAX_COUNT 2

#define DATA_GET 0X01
#define DEVICE_HEART 0X02
#endif